import type { NextPage } from "next";
import Head from "next/head";
import { ReactNode, useState } from "react";

const Home: NextPage = () => {
    const [url, setUrl] = useState<string>("");
    const [data, setData] = useState<string>("");

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setUrl(e.target.value);
    };

    const handleClick = () => {
        console.log(url);
        fetch(url)
            .then(async res => {
                const resp = await res.text();
                setData(resp);
                return resp;
            })
            // .then(async html => {
            //     const res = await fetch("/api/hello", {
            //         method: "POST",
            //         body: html,
            //     });
            //     await res.json();
            // })
            .catch(err => console.log(err));
    };

    const handleSubmitClick = async () => {
        let arr: string[] = [];
        const images = document.querySelectorAll("img");

        Array.from(images).forEach((item: any) => {
            const src = item.getAttribute("src");
            if (!src.includes("/static/")) {
                arr.push(src);
            }
        });

        if (arr.length > 0) {
            const res = await fetch("/api/multiple-download", {
                method: "POST",
                body: JSON.stringify(arr),
            });
            await res.json();
        }
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div
                style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    alignItems: "center",
                    minHeight: "100vh",
                }}
            >
                <input onChange={handleChange} value={url} type={"text"} />
                <button onClick={handleClick} style={{ marginTop: "10px" }}>
                    Get Data
                </button>

                <button onClick={handleSubmitClick} style={{ marginTop: "10px" }}>
                    Submit Data
                </button>

                <div dangerouslySetInnerHTML={{ __html: data }} />
            </div>
        </div>
    );
};

export default Home;
